# Generated by Django 4.1.6 on 2023-04-18 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=1000)),
                ('productId', models.CharField(default='0', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
